config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:passwords], controllers:{
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy'
  end

 scope module: :public do
   post 'orders/confirm' => 'orders#confirm'
   root to: "homes#top"
   get 'about' => 'homes#about'
   resources :items, only: [:index,:show]
   resources :genres, only: [:show]
   get 'customers/unsubscribe' => 'customers#unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw'
   get 'customers/my_page' => 'customers#show'
   get 'customers/information/edit' => 'customers#edit'
   patch 'customers/information' => 'customers#update'
   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
   resources :cart_items, only: [:index,:update,:destroy,:create]
   get 'orders/done' => 'orders#done'
   resources :orders, only: [:new,:create,:index,:show]
   resources :shopping_addresses, only: [:index,:edit,:create,:update,:destroy]
 end
 namespace :admin do
   root to: "homes#top"
   resources :items, only: [:index,:new,:create,:show,:edit,:update,:destroy]
   resources :genres, only: [:index,:create,:edit,:update,:destroy]
   resources :customers, only: [:index,:show,:edit,:update]
   resources :orders, only: [:index,:show,:update]
   resources :order_details, only: [:update]
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
    self.item.add_tax_price*self.quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :shopping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  def full_name
    last_name + first_name
  end
end

app/models/genere.rb
class Genere < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :name,presence:true
  validates :address,presence:true
  validates :postcode,presence:true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }

  def add_tax_price
    (self.price * 1.10).round
  end

  def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
    self.item.add_tax_price*self.quantity
  end



end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2, finish: 3 }

  def add_tax_price
    (self.price * 1.10).round
  end

  def sum_price
    self.item.add_tax_price*self.quantity
  end

end

app/models/shopping_address.rb
class ShoppingAddress < ApplicationRecord
  belongs_to :customer
  
  def new
  @address = ShoppingAddres 
  end 
  def address_display
  '〒' + postcode + ' ' + address + ' ' + name 
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
     before_action :authenticate_admin!
 def index
    @customers = Customer.order("created_at DESC").page(params[:page]).per(5)
 end
 
 def show
    @customer = Customer.find(params[:id])
 end
 
 def edit
    @customer = Customer.find(params[:id])
 end     
    
 def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
 end
 
 private 

 def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:address,:postcode,:phone_number,:email,:is_deleted)
 end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
     before_action :authenticate_admin!
 def index
    @genre = Genre.new
    @genres = Genre.all
 end
  
 def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
 end
 
 def edit
    @genre = Genre.find(params[:id])
 end     
    
 def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
 end
    
 def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
 end   
    
 private

 def genre_params
   params.require(:genre).permit(:name)
 end    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
     before_action :authenticate_admin!
 def top 
    @orders = Order.order("created_at DESC").page(params[:page]).per(5)
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
      before_action :authenticate_admin!
  def index
    @items = Item.all.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

    def item_params
      params.require(:item).permit(:name, :introduction, :price, :status, :image ,:genre_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        customers_my_page_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    else
        new_admin_session_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
     <h4 class="bg-primary text-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
     <%= form_with model: [:admin,@customer],  method: :patch do |f| %>
     <table>
      <tr>
       <td>会員ID</td>
       <td>　　　　　　<%= @customer.id %></td>
      </tr>
      <tr>
       <td>氏名</td>
       <td>　　　　　　<%= f.text_field :last_name, autofocus: true %>　　<%= f.text_field :first_name, autofocus: true %></td>
      </tr>
      <tr>
       <td>フリガナ</td>
       <td>　　　　　　<%= f.text_field :last_name_kana, autofocus: true %>　　<%= f.text_field :first_name_kana, autofocus: true %></td>
      </tr>
      <tr>
       <td>郵便番号（ハイフンなし)</td>
       <td>　　　　　　<%= f.text_field :postcode, autofocus: true %></td>
      </tr>
      <tr>
       <td>住所</td>
       <td>　　　　　　<%= f.text_field :address, autofocus: true %></td>
      </tr>
      <tr>
       <td>電話番号（ハイフンなし）</td>
       <td>　　　　　　<%= f.text_field :phone_number, autofocus: true %></td>
      </tr>
      <tr>
       <td>メールアドレス</td>
       <td>　　　　　　<%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
      </tr>
      <tr>
       <td><%= f.radio_button :is_deleted, 'false' %>
           <%= f.label :is_deleted, '有効' %></td>
       <td><%= f.radio_button :is_deleted, 'true' %>
           <%= f.label :is_deleted, '退会' %></td>
      </tr>
      <tr>
       <td><%= f.submit '変更を保存', class: 'btn btn-success  rounded-pill'%></td>
      </tr>
     </table>
     <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
 <div class='container px-5 px-sm-0'>
  <div class='row'>
   <div class='col-md-2'><u><h4>会員一覧</h4></u></div>
   <div class='col-md-8'>
     <table class='table table-hover table-inverse '>
    <thead>
     <tr class="table-info">
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
     </tr> 
    </thead>    
    <tbody>
    <% @customers.each do |customer| %>
     <tr>
      <td><%= customer.id %></td> 
      <td><%= link_to admin_customer_path(customer.id) do %><%= customer.last_name %><%= customer.first_name %><% end %></td>
      <td><%= customer.email %></td>
      <td><% if customer.is_deleted == false %>
  		   <p class="text-success">有効</p>
  	       <% else %>
  		   <p class="text-secondary">退会</p>
  	       <% end %></td>
          <% end %>
     </tr>
     <tr>
      <td></td>
      <td></td>
      <td><%= paginate @customers %></td>
     </tr> 
    </tbody> 
   </table>
  </div> 
  <div class='col-md-2'></div>
 </div>
</div>   
    

app/views/admin/customers/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
   <div class='mx-auto'>
    <h4 class="bg-primary text-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
     <table>
      <tr>
       <td>会員ID</td>
       <td>　　　　　<%= @customer.id %></td>
      </tr>
      <tr>
       <td>氏名</td>
       <td>　　　　　<%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>
      <tr>
       <td>フリガナ</td>
       <td>　　　　　<%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
      </tr>
      <tr> 
       <td>郵便番号</td>
       <td>　　　　　<%= @customer.postcode %></td>
      </tr>
      <tr>
       <td>住所</td>
       <td>　　　　　<%= @customer.address %></td>
      </tr>
      <tr>
       <td>電話番号</td>
       <td>　　　　　<%= @customer.phone_number %></td>
      </tr>
      <tr>
       <td>メールアドレス</td>
       <td>　　　　　<%= @customer.email %></td>
      </tr>
      <tr>
       <td>会員ステータス</td>
        <% if @customer.is_deleted == false %>
  	    	<td class="text-success">　　　　　　有効</td>
  	     <% else %>
  	    	<td class="text-secondary">　　　　　退会</td>
  	     <% end %>
      </tr>
      <tr>
       <td><%= link_to '編集する', edit_admin_customer_path(@customer), class: "btn btn-sm btn-success  rounded-pill" %></td>
       <td><%= link_to '注文履歴一覧を見る', admin_orders_path, class: 'btn btn-sm btn-primary  rounded-pill' %></td>
      </tr>
     </table> 
   </div>    
  </div>
 </div> 