config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:passwords], controllers:{
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy'
  end

 scope module: :public do
   post 'orders/confirm' => 'orders#confirm'
   root to: "homes#top"
   get 'about' => 'homes#about'
   resources :items, only: [:index,:show]
   resources :genres, only: [:show]
   get 'customers/unsubscribe' => 'customers#unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw'
   get 'customers/my_page' => 'customers#show'
   get 'customers/information/edit' => 'customers#edit'
   patch 'customers/information' => 'customers#update'
   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
   resources :cart_items, only: [:index,:update,:destroy,:create]
   get 'orders/done' => 'orders#done'
   resources :orders, only: [:new,:create,:index,:show]
   resources :shopping_addresses, only: [:index,:edit,:create,:update,:destroy]
 end
 namespace :admin do
   root to: "homes#top"
   resources :items, only: [:index,:new,:create,:show,:edit,:update,:destroy]
   resources :genres, only: [:index,:create,:edit,:update,:destroy]
   resources :customers, only: [:index,:show,:edit,:update]
   resources :orders, only: [:index,:show,:update]
   resources :order_details, only: [:update]
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
    self.item.add_tax_price*self.quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :shopping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  def full_name
    last_name + first_name
  end
end

app/models/genere.rb
class Genere < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :name,presence:true
  validates :address,presence:true
  validates :postcode,presence:true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }

  def add_tax_price
    (self.price * 1.10).round
  end

  def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
    self.item.add_tax_price*self.quantity
  end



end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2, finish: 3 }

  def add_tax_price
    (self.price * 1.10).round
  end

  def sum_price
    self.item.add_tax_price*self.quantity
  end

end

app/models/shopping_address.rb
class ShoppingAddress < ApplicationRecord
  belongs_to :customer
  
  def new
  @address = ShoppingAddres 
  end 
  def address_display
  '〒' + postcode + ' ' + address + ' ' + name 
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
     before_action :authenticate_admin!
 def index
    @genre = Genre.new
    @genres = Genre.all
 end
  
 def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
 end
 
 def edit
    @genre = Genre.find(params[:id])
 end     
    
 def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
 end
    
 def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
 end   
    
 private

 def genre_params
   params.require(:genre).permit(:name)
 end    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
     before_action :authenticate_admin!
 def top 
    @orders = Order.order("created_at DESC").page(params[:page]).per(5)
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
      before_action :authenticate_admin!
  def index
    @items = Item.all.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

    def item_params
      params.require(:item).permit(:name, :introduction, :price, :status, :image ,:genre_id)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
      before_action :authenticate_admin!
 def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = OrderDetail.where(order_id: @order.id)
    @cart_items = Customer.find(params[:id]).cart_items.all
    @sum = 0
    @order_details.each do |order_detail|
      @sum += order_detail.sum_price
    end

    @total = @sum + postage
 end
 
 def postage
    @postage = 800
 end

 def update
     @order = Order.find(params[:id])
     if @order.update(order_params)
       if @order.status == "confirm_payment"
          @order.order_details.each do |order_detail|
          order_detail.update(status: "waiting_manufacture" )
          end
       end
       redirect_to admin_order_path
     else
       render :show
     end
 end
 
 private  
 
 def customer_params
    params.require(:customer).permit(:last_name,:first_name)
 end
 
 def order_params
    params.require(:order).permit(:name,:address,:payment_method,
                                  :status,:price,:customer_id,:created_at)
 end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        customers_my_page_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    else
        new_admin_session_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='mx-auto'>
     <h4 class='bg-dark text-light'>ジャンル編集</h4></br>
      <div class='row'> 
       ジャンル名　　
       <%= form_with model: [:admin,@genre],  method: :patch do |f| %>
       <%= f.text_field :name %>　　
       <%= f.submit '変更を保存', class: 'btn btn-success rounded-pill'%>
       <% end %> 
      </div>
    </div>
  </div>
</div>       

app/views/admin/genres/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
   <div class='mx-auto'>
   <h4 class='bg-dark text-light'>ジャンル一覧・追加</h4></br>
   <div class='row'>
    <%= form_with model: [:admin,@genre] do |f| %>
     ジャンル名　　
    <%= f.text_field :name, placeholder:"ジャンル名" %>　　
    <%= f.submit '新規登録', class: 'btn btn-success rounded-pill' %>
    <% end %>
    </div></br>
    <table class='table table-hover table-inverse'>
     <thead class='thead-dark'>
      <tr>
       <th>ジャンル</th>
      </tr>
     </thead>
     <tbody>
      <% @genres.each do |genre| %>
       <tr>
        <td><%= genre.name %></td>
        <td>　　</td>
        <td><%= link_to '編集する', edit_admin_genre_path(genre), class: 'btn btn-success rounded-pill'%></td>
        <td><%= link_to '削除', [:admin,genre], method: :delete, class: "btn btn-sm btn-danger rounded-pill"%></td>
       <% end %>
       </tr>
     </tbody>
    </table>
   </div> 
  </div>
 </div> 

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-2">
      <br><h4>　　<u>商品編集</u></h4>
    </div>
    <div class="col-lg-6"><br>
    <%= form_with model: [:admin,@item] do |f| %>
      <table>
        <tr>　</tr>
        <tr>
          <th>商品画像</th>
          <th></th>
          <th><%= f.file_field :image, accept: "image/*" %></th>
        </tr>
        <tr>
          <th>商品名</th>
          <th>　</th>
          <th><%= f.text_field :name, size: 30 %></th>
        </tr>
        <tr>
          <th>商品説明</th>
          <th></th>
          <th><%= f.text_area :introduction, size: "33x5" %></th>
        </tr>
        <tr>
          <th>ジャンル</th>
          <th></th>
          <th><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %></th>
        </tr>
        <tr>
          <th>税抜価格</th>
          <th></th>
          <th><%= f.text_field :price, size: 30 %>円</th>
        </tr>
        <tr>
          <th>
          販売ステータス
          </th>
          <th></th>
          <th>
          <%= f.radio_button :status, 'true' %>
          <%= f.label :status, '販売中' %>
          <%= f.radio_button :status, 'false' %>
          <%= f.label :status, '販売停止中' %>
          </th>
        </tr>
        <tr>
          <th></th>
          <th>　</th>
          <th>
            <%= f.submit '変更を保存', class: 'btn btn-success rounded-pill' %>
          </th>
        </tr>
      </table>
      <% end %>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-10">
    <br>
    <h4><u>商品一覧</u></h4>
    <br>
    <table class="table table-hover rounded">
      <thead>
        <tr class="table-info">
          <th>商品ID　</th>
          <th>商品名　</th>
          <th>商品画像</th>
          <th>税抜価格　</th>
          <th>ジャンル　</th>
          <th>ステータス　</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
            <%= image_tag item.image, size:'50x50' %><% end %>
          </td>
          <td><%= item.price %>円</td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.status == true %>
      					<p class="text-success">販売中</p>
      			<% else %>
      					<p class="text-secondary">販売停止中</p>
      			<% end %>
          </td>
          <td>
            <%= link_to '削除', [:admin,item], method: :delete, class: "btn btn-sm btn-danger rounded-pill"%>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto" style="width: 200px;"><%= paginate @items %></div>
    </div>
    <div class="col-lg-1">
      <%=  link_to new_admin_item_path do %>
      <button type="button" class="btn btn-outline-warning rounded-circle p-0" style="width:2rem;height:2rem;">＋</button>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-2">
      <h4><u>商品新規登録</u></h4>
    </div>
    <div class="col-lg-6">
      <%= form_with model: [:admin,@item] do |f| %>
      <table>
        <tr>　</tr>
        <tr>
          <th>商品画像</th>
          <th></th>
          <th><%= f.file_field :image, accept: "image/*" %></th>
        </tr>
        <tr>
          <th>商品名</th>
          <th>　</th>
          <th><%= f.text_field :name, placeholder: "商品名", size: 30 %></th>
        </tr>
        <tr>
          <th>商品説明</th>
          <th></th>
          <th><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "33x5" %></th>
        </tr>
        <tr>
          <th>ジャンル</th>
          <th></th>
          <th><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %></th>
        </tr>
        <tr>
          <th>税抜価格</th>
          <th></th>
          <th><%= f.text_field :price, placeholder: "1000", size: 30 %>円</th>
        </tr>
        <tr>
          <th>
          販売ステータス
          </th>
          <th></th>
          <th>
          <%= f.radio_button :status, 'true' %>
          <%= f.label :status, '販売中' %>
          <%= f.radio_button :status, 'false' %>
          <%= f.label :status, '販売停止中' %>
          </th>
        </tr>
        <tr>
          <th></th>
          <th>　</th>
          <th>
            <%= f.submit '新規登録', class: 'btn btn-success rounded-pill' %>
          </th>
        </tr>
      </table>
      <% end %>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-3">
      <br><h4><u>商品詳細</u></span></h4>
      <%= image_tag @item.image, size:'250x250' %>
    </div>
    <div class="col-lg-7"><br><br><br>
      <table>
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格<br>（税抜価格）</td>
          <td><%= @item.add_tax_price %>（<%= @item.price %>）円</td>
        </tr>
        <tr>
          <td>販売ステータス　</td>
          <th>
            <% if @item.status == true %>
      					<p class="text-success">販売中</p>
      			<% else %>
      					<p class="text-secondary">販売停止中</p>
      			<% end %>
      		</th>
        </tr>
          <td></td>
          <td><%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-sm btn-success rounded-pill" %></td>
        </tr>
      </table>
    </div>
    <div class="col-lg-1"></div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="row">
  <u><h4>注文履歴詳細</h4></u>
 </div>
 
 <div class="row">
  <table>
     <tr>
      <td>購入者</td>
      <td><%= link_to @order.customer.full_name,admin_customer_path(@order.customer) %></td>
     </tr>
     <tr>
      <td>注文日</td>
      <td><%= @order.created_at.strftime('%Y/%m/%d')  %></td>
     </tr>
     <tr>
       <td>配送先</td>
       <td><%= @order.address %></td>
     <tr>
     </tr>
     <tr>
       <td>支払方法</td>
       <td><%= @order.payment_method_i18n %></td>
     </tr>
     <tr>
      <td>注文ステータス</td>
      <td><%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
          <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
       　　<%= f.submit "更新", class:"btn btn-success rounded-pill" %>
       　　<% end %>
    　</td>
     </tr>
     <tr>
      <td>　</td>
      <td>　</td>
     </tr>
  </table>
 </div>

  <div class="row">
   <div class="col-lg-8" >
    <table class='table table-hover table-inverse'>
      <thead>
        <tr class="table-info">
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
       <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.item.add_tax_price%></td>
          <td><%= order_detail.quantity %></td>
          <td><%= order_detail.quantity * order_detail.item.add_tax_price %></td>
          <td>
           <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
           <%= f.hidden_field :order_detail_id, value: order_detail.id %>
           <%= f.select :status, OrderDetail.statuses.keys.map {|k| [I18n.t("enums.order_detail.status.#{k}"), k]} %>
           <%= f.submit "更新", class:"btn btn-success rounded-pill" %>
           <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
   </div>
    <div class="col-lg-4">
     <table class='table under'>
      <tr>
        <th>商品合計</th>
        <td><%= @sum %></td>
      </tr>
      <tr>
        <th>送料</th>
        <td><%= @postage %></td>
      </tr>
      <tr>
        <th>請求合計金額</th>
        <td><%= @total %></td>
      </tr>
     </table>
    </div>
  </div>
</div>