config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:passwords], controllers:{
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy'
  end

 scope module: :public do
   post 'orders/confirm' => 'orders#confirm'
   root to: "homes#top"
   get 'about' => 'homes#about'
   resources :items, only: [:index,:show]
   resources :genres, only: [:show]
   get 'customers/unsubscribe' => 'customers#unsubscribe'
   patch 'customers/withdraw' => 'customers#withdraw'
   get 'customers/my_page' => 'customers#show'
   get 'customers/information/edit' => 'customers#edit'
   patch 'customers/information' => 'customers#update'
   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
   resources :cart_items, only: [:index,:update,:destroy,:create]
   get 'orders/done' => 'orders#done'
   resources :orders, only: [:new,:create,:index,:show]
   resources :shopping_addresses, only: [:index,:edit,:create,:update,:destroy]
 end
 namespace :admin do
   root to: "homes#top"
   resources :items, only: [:index,:new,:create,:show,:edit,:update,:destroy]
   resources :genres, only: [:index,:create,:edit,:update,:destroy]
   resources :customers, only: [:index,:show,:edit,:update]
   resources :orders, only: [:index,:show,:update]
   resources :order_details, only: [:update]
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
    self.item.add_tax_price*self.quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :shopping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  def full_name
    last_name + first_name
  end
end

app/models/genere.rb
class Genere < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :image

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :name,presence:true
  validates :address,presence:true
  validates :postcode,presence:true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }

  def add_tax_price
    (self.price * 1.10).round
  end

  def sum_price # 実際に作成したサイトは税金も算出していたのでメソッドを記載していました
    self.item.add_tax_price*self.quantity
  end



end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2, finish: 3 }

  def add_tax_price
    (self.price * 1.10).round
  end

  def sum_price
    self.item.add_tax_price*self.quantity
  end

end

app/models/shopping_address.rb
class ShoppingAddress < ApplicationRecord
  belongs_to :customer
  
  def new
  @address = ShoppingAddres 
  end 
  def address_display
  '〒' + postcode + ' ' + address + ' ' + name 
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
     before_action :authenticate_admin!
 def top 
    @orders = Order.order("created_at DESC").page(params[:page]).per(5)
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
      before_action :authenticate_admin!
  def index
    @items = Item.all.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

    def item_params
      params.require(:item).permit(:name, :introduction, :price, :status, :image ,:genre_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_root_path
    else
        customers_my_page_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    else
        new_admin_session_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-white bg-white">
    <div class="container">
      <%= link_to root_path,title:"top" do %><%= image_tag 'logo.jpg', size: "125x125" %><% end %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="m-1">
            <%= link_to admin_items_path,class: "btn btn-outline-secondary rounded-pill",title:"item list" do %>
            <i class="fas fa-birthday-cake"></i> 商品一覧
            <% end %>
          </li>
          <li class="m-1">
            <%=  link_to admin_customers_path,class: "btn btn-outline-secondary rounded-pill",title:"customer list" do %>
            <i class="fas fa-address-book"></i> 会員一覧
            <% end %>
          </li>
          <li class="m-1">
            <%=  link_to admin_root_path ,class: "btn btn-outline-secondary rounded-pill",title:"order list" do %>
            <i class="fas fa-shopping-cart"></i> 注文履歴一覧
            <% end %>
          </li>
          <li class="m-1">
            <%=  link_to admin_genres_path ,class: "btn btn-outline-secondary rounded-pill",title:"genre list" do %>
            <i class="fas fa-mug-hot"></i> ジャンル一覧
            <% end %>
          </li>
          <li class="m-1">
            <%= link_to destroy_admin_session_path, method: :delete,class: "btn btn-outline-secondary rounded-pill",title:"logout" do %>
            <i class="fas fa-sign-out-alt"></i>
            <% end %>
          </li>
        <% elsif customer_signed_in? %>
          <li class="m-1">
            <%= link_to customers_my_page_path,class: "btn btn-outline-secondary rounded-pill",title:"my page" do %>
            <i class="fas fa-address-card"></i> <%= current_customer.full_name %>
            <% end %>
          </li>
          <li class="m-1">
            <%=  link_to items_path,class: "btn btn-outline-secondary rounded-pill",title:"item list" do %>
            <i class="fas fa-birthday-cake"></i> 商品一覧
            <% end %>
          </li>
          <li class="m-1">
            <%=  link_to cart_items_path ,class: "btn btn-outline-secondary rounded-pill",title:"cart" do %>
            <i class="fas fa-shopping-cart"></i> カート
            <% end %>
          </li>
          <li class="m-1">
            <%= link_to destroy_customer_session_path, method: :delete,class: "btn btn-outline-secondary rounded-pill",title:"logout" do %>
            <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="m-1">
            <%= link_to about_path, data: {"turbolinks" => false},class: "btn btn-outline-secondary rounded-pill",title:"about" do %>
            <i class="fas fa-store"></i> About
            <% end %>
          </li>
          <li class="m-1">
            <%= link_to items_path,class: "btn btn-outline-secondary rounded-pill",title:"item list" do %>
            <i class="fas fa-birthday-cake"></i> 商品一覧
            <% end %>
          </li>
          <li class="m-1">
            <%= link_to new_customer_registration_path,class: "btn btn-outline-secondary rounded-pill",title:"sign up" do %>
            <i class="fas fa-user-edit"></i> 新規登録
            <% end %>
          </li>
          <li class="m-1">
            <%= link_to new_customer_session_path ,class: "btn btn-outline-secondary rounded-pill",title:"sign in" do %>
            <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
          <li class="m-1">
            <%= link_to new_admin_session_path ,class: "btn btn-outline-secondary rounded-pill",title:"admin" do %>
            <i class="fas fa-id-badge"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="search_form">
          <%= form_with url: root_path, local: true, method: :get do |f| %>
          <%= f.text_field :name, placeholder: "文字を入力", size: 10 %>
          <%= f.submit"検索" %>
          <% end %>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/cccf4986d1.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        $('.slider').bxSlider({
          auto: true,
          pause: 3000,
        });
      });
    </script>
  </head>
  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
  </body>
  <footer>
    <div class='container mt-5'>
  	　<div class='row'>
    	  <div class='mx-auto'>
    		<p>CopyRight TeamH.inc</p>
    	  </div>
      </div>
    </div>
  </footer>
</html>